### ISSUE TITLE
how can I sanitize params[:sorted]?

### ISSUE THREAD

**Issue by jogaco** [mynameisrufus/sorted-activerecord#1]
If I manipulate the params, I can provoke a 500 error,  or even could order by a private attribute.

Very useful gem by the way. I am still in sorted 1.0.1 but plan to upgrade asap.

**Comment by mynameisrufus** [comment]
What are you thinking? Something like:

``` ruby
@users = User.sorted(
  sort: params[:sort],
  default: [[email: 'asc']],
  allow: [:email, :phone]
)
```

**Comment by jogaco** [comment]
Either via hash or via optional params: sorted(sort, default =  nil, allow = nil).
That would be awesome!

I don't know if it would be possible and easy to allow by default only attributes present in the relation?

On another note, is there any reason the last versions require activerecord >=4.0? 3.2 is my current version :(

**Comment by mynameisrufus** [comment]
I think that's possible `Model.column_names` returns what is needed I think.

I will try and get it quacking like http://guides.rubyonrails.org/active_record_querying.html#ordering also:

``` ruby
@users = User.sorted(sort: [{email: :asc}], order: [{phone: :desc}])
```

**Comment by jogaco** [comment]
Great!

**Comment by mynameisrufus** [comment]
I have made the changes, I went with a `whitelist` argument because people could us alias names such as `foo AS bar` for example.

Support for ruby 1.9 is dropped also, this gem uses named arguments so will not work with 1.9.

Sorry about AR 3.2, I took advantage of some 4.x features in the `order` scope that I did not want to pass up so perhaps hold off using this gem until you are on Rails 4.x.
